<?php

namespace App\Database\Seeds;

use CodeIgniter\Database\Seeder;

class Entities extends Seeder
{
    public function run()
    {
        // cargamos datos base de la tabla para grupo
        $dataEntities = [
            ['ENTS_name' => 'Unidad para las Víctimas', 'ENTS_description' => 'Unidad para las Víctimas'],
            ['ENTS_name' => 'Agencia Nacional de Tierras - ANT ', 'ENTS_description' => 'Agencia Nacional de Tierras - ANT '],
            ['ENTS_name' => 'Agencia de Desarrollo Rural - ADR ', 'ENTS_description' => 'Agencia de Desarrollo Rural - ADR '],
            ['ENTS_name' => 'Banco Agrario de Colombia S.A.', 'ENTS_description' => 'Banco Agrario de Colombia S.A.'],
            ['ENTS_name' => 'Banco de Comercio Exterior de Colombia - BANCOLDEX', 'ENTS_description' => 'Banco de Comercio Exterior de Colombia - BANCOLDEX'],
            ['ENTS_name' => 'Centro Nacional de Memoria Histórica de Colombia', 'ENTS_description' => 'Centro Nacional de Memoria Histórica de Colombia'],
            ['ENTS_name' => 'Agencia para la Reincorporacion y la Normalizacion - ARN ', 'ENTS_description' => 'Agencia para la Reincorporacion y la Normalizacion - ARN '],
            ['ENTS_name' => 'Consejo Superior de la Judicatura', 'ENTS_description' => 'Consejo Superior de la Judicatura'],
            ['ENTS_name' => 'Defensoría del Pueblo', 'ENTS_description' => 'Defensoría del Pueblo'],
            ['ENTS_name' => 'Departamento Administrativo para la Prosperidad Social - DPS ', 'ENTS_description' => 'Departamento Administrativo para la Prosperidad Social - DPS '],
            ['ENTS_name' => 'Departamento Nacional de Planeación - DNP', 'ENTS_description' => 'Departamento Nacional de Planeación - DNP'],
            ['ENTS_name' => 'Dirección para la Acción Integral contra Minas Antipersonal - DAICMA', 'ENTS_description' => 'Dirección para la Acción Integral contra Minas Antipersonal - DAICMA'],
            ['ENTS_name' => 'Consejeria de los derechos Humanos de la  Presidencia de la Republica ', 'ENTS_description' => 'Consejeria de los derechos Humanos de la  Presidencia de la Republica '],
            ['ENTS_name' => 'Fiscalía General de la Nación', 'ENTS_description' => 'Fiscalía General de la Nación'],
            ['ENTS_name' => 'Fondo para el Financiamiento del Sector Agropecuario - FINAGRO', 'ENTS_description' => 'Fondo para el Financiamiento del Sector Agropecuario - FINAGRO'],
            ['ENTS_name' => 'Fundacion Batuta', 'ENTS_description' => 'Fundacion Batuta'],
            ['ENTS_name' => 'Instituto Colombiano de Bienestar Familiar - ICBF', 'ENTS_description' => 'Instituto Colombiano de Bienestar Familiar - ICBF'],
            ['ENTS_name' => 'Instituto Colombiano de Crédito y Estudios en el Exterior - ICETEX', 'ENTS_description' => 'Instituto Colombiano de Crédito y Estudios en el Exterior - ICETEX'],
            ['ENTS_name' => 'Instituto Geográfico Agustín Codazzi - IGAC', 'ENTS_description' => 'Instituto Geográfico Agustín Codazzi - IGAC'],
            ['ENTS_name' => 'Instituto Nacional de Medicina Legal y Ciencias Forenses', 'ENTS_description' => 'Instituto Nacional de Medicina Legal y Ciencias Forenses'],
            ['ENTS_name' => 'Ministerio de Agricultura y Desarrollo Rural', 'ENTS_description' => 'Ministerio de Agricultura y Desarrollo Rural'],
            ['ENTS_name' => 'Ministerio de Comercio Industria y Turismo', 'ENTS_description' => 'Ministerio de Comercio Industria y Turismo'],
            ['ENTS_name' => 'Ministerio de Defensa Nacional', 'ENTS_description' => 'Ministerio de Defensa Nacional'],
            ['ENTS_name' => 'Ministerio de Educación Nacional', 'ENTS_description' => 'Ministerio de Educación Nacional'],
            ['ENTS_name' => 'Ministerio de Justicia y del Derecho ', 'ENTS_description' => 'Ministerio de Justicia y del Derecho '],
            ['ENTS_name' => 'Ministerio de Salud y Protección Social', 'ENTS_description' => 'Ministerio de Salud y Protección Social'],
            ['ENTS_name' => 'Ministerio de Vivienda, Ciudad y Territorio', 'ENTS_description' => 'Ministerio de Vivienda, Ciudad y Territorio'],
            ['ENTS_name' => 'Ministerio del Interior', 'ENTS_description' => 'Ministerio del Interior'],
            ['ENTS_name' => 'Ministerio del Trabajo', 'ENTS_description' => 'Ministerio del Trabajo'],
            ['ENTS_name' => 'Policía Nacional de Colombia', 'ENTS_description' => 'Policía Nacional de Colombia'],
            ['ENTS_name' => 'Registraduría Nacional del Estado Civil', 'ENTS_description' => 'Registraduría Nacional del Estado Civil'],
            ['ENTS_name' => 'Servicio Nacional de Aprendizaje - SENA', 'ENTS_description' => 'Servicio Nacional de Aprendizaje - SENA'],
            ['ENTS_name' => 'Superintendencia de Notariado y Registro', 'ENTS_description' => 'Superintendencia de Notariado y Registro'],
            ['ENTS_name' => 'Unidad Administrativa Especial del Servicio Público de Empleo', 'ENTS_description' => 'Unidad Administrativa Especial del Servicio Público de Empleo'],
            ['ENTS_name' => 'Unidad de Gestión de Restitución de Tierras Despojadas - URT', 'ENTS_description' => 'Unidad de Gestión de Restitución de Tierras Despojadas - URT'],
            ['ENTS_name' => 'Unidad Nacional de Proteccion - UNP', 'ENTS_description' => 'Unidad Nacional de Proteccion - UNP'],
            ['ENTS_name' => 'Fondo Nacional de Garantias - FNG', 'ENTS_description' => 'Fondo Nacional de Garantias - FNG'],
            ['ENTS_name' => 'Procuraduria General de la Nacion ', 'ENTS_description' => 'Procuraduria General de la Nacion '],
            ['ENTS_name' => 'Agencia de Renovacion del Territorio ', 'ENTS_description' => 'Agencia de Renovacion del Territorio '],
            ['ENTS_name' => 'Unidad Administrativa Especial de Organizaciones Solidarias', 'ENTS_description' => 'Unidad Administrativa Especial de Organizaciones Solidarias'],
            ['ENTS_name' => 'Superintendencia de Industria y Comercio ', 'ENTS_description' => 'Superintendencia de Industria y Comercio '],
            ['ENTS_name' => 'MINTIC', 'ENTS_description' => 'MINTIC'],
            ['ENTS_name' => 'Ministerio de Cultura', 'ENTS_description' => 'Ministerio de Cultura'],
            ['ENTS_name' => 'Cooperación Internacional', 'ENTS_description' => 'Cooperación Internacional'],
            ['ENTS_name' => 'Organismo de control', 'ENTS_description' => 'Organismo de control'],
            ['ENTS_name' => 'Entidad privada', 'ENTS_description' => 'Entidad privada'],
            ['ENTS_name' => 'Persona natural', 'ENTS_description' => 'Persona natural'],
            ['ENTS_name' => 'Otros', 'ENTS_description' => 'Otros'],

        ];
        $this->db->table('entities')->insertBatch($dataEntities);



        // cargamos datos base para aplicaciones
        $dataAplications = [
            ['APPS_name' => 'RUV', 'APPS_description' => 'REGISTRO UNICO DE VICTIMAS'],
            ['APPS_name' => 'SIRAV', 'APPS_description' => 'SISTEMA DE INFORMACION REGISTRO ATENCION A VICTIMAS'],
            ['APPS_name' => 'SIPOD', 'APPS_description' => 'SISTEMA DE INFORMACION PARA LA POBLACION DESPLAZADA'],
            ['APPS_name' => 'ASDOC', 'APPS_description' => 'ASDOC'],
            ['APPS_name' => 'VIVANTO', 'APPS_description' => 'VIVANTO'],

        ];
        $this->db->table('apps')->insertBatch($dataAplications);

        // cargamos datos base para dependecias
        $dataDependencies = [
            ['DPND_name' => 'Dirección de Gestión Interinstitucional - DGI - UARIV', 'DPND_description' => 'Dirección de Gestión Interinstitucional - DGI - UARIV'],
            ['DPND_name' => 'Subdirección SNARIV - UARIV', 'DPND_description' => 'Subdirección SNARIV - UARIV'],
            ['DPND_name' => 'Subdirección C Nación Territorio - UARIV', 'DPND_description' => 'Subdirección C Nación Territorio - UARIV'],
            ['DPND_name' => 'Subdirección de Participación - UARIV', 'DPND_description' => 'Subdirección de Participación - UARIV'],
            ['DPND_name' => 'Dirección de Gestión Social Humanitaria DGSH - UARIV', 'DPND_description' => 'Dirección de Gestión Social Humanitaria DGSH - UARIV'],
            ['DPND_name' => 'Subdirección de Prevención y Atención a Emergencias SPAE - UARIV', 'DPND_description' => 'Subdirección de Prevención y Atención a Emergencias SPAE - UARIV'],
            ['DPND_name' => 'Subdirección de Asistencia y Atención Humanitaria SAAH - UARIV', 'DPND_description' => 'Subdirección de Asistencia y Atención Humanitaria SAAH - UARIV'],
            ['DPND_name' => 'Dirección de Reparaciones - UARIV', 'DPND_description' => 'Dirección de Reparaciones - UARIV'],
            ['DPND_name' => 'Subdirección de Reparación Individual - UARIV', 'DPND_description' => 'Subdirección de Reparación Individual - UARIV'],
            ['DPND_name' => 'Subdirección de Reparación Colectiva - UARIV', 'DPND_description' => 'Subdirección de Reparación Colectiva - UARIV'],
            ['DPND_name' => 'Dirección de Registro y Gestión de la Información DRGI - UARIV', 'DPND_description' => 'Dirección de Registro y Gestión de la Información DRGI - UARIV'],
            ['DPND_name' => 'Subdirección de Valoración y Registro SVR - UARIV', 'DPND_description' => 'Subdirección de Valoración y Registro SVR - UARIV'],
            ['DPND_name' => 'Subdirección Red Nacional de Información SRNI - UARIV', 'DPND_description' => 'Subdirección Red Nacional de Información SRNI - UARIV'],
            ['DPND_name' => 'Dirección de Asuntos Étnicos DAE - UARIV', 'DPND_description' => 'Dirección de Asuntos Étnicos DAE - UARIV'],
            ['DPND_name' => 'Oficina Asesora de Comunicaciones - UARIV', 'DPND_description' => 'Oficina Asesora de Comunicaciones - UARIV'],
            ['DPND_name' => 'Oficina Asesora de Planeación - UARIV', 'DPND_description' => 'Oficina Asesora de Planeación - UARIV'],
            ['DPND_name' => 'Oficina Asesora Jurídica OAJ - UARIV', 'DPND_description' => 'Oficina Asesora Jurídica OAJ - UARIV'],
            ['DPND_name' => 'Dirección General - UARIV', 'DPND_description' => 'Dirección General - UARIV'],
            ['DPND_name' => 'Subdirección General - UARIV', 'DPND_description' => 'Subdirección General - UARIV'],
            ['DPND_name' => 'Oficina de Control Interno - UARIV', 'DPND_description' => 'Oficina de Control Interno - UARIV'],
            ['DPND_name' => 'Oficina de Tecnologías de la Información - UARIV', 'DPND_description' => 'Oficina de Tecnologías de la Información - UARIV'],
            ['DPND_name' => 'Secretaría General - UARIV', 'DPND_description' => 'Secretaría General - UARIV'],
            ['DPND_name' => 'Control Interno', 'DPND_description' => 'Control Interno'],
            ['DPND_name' => 'Directora territorial Antioquia - UARIV', 'DPND_description' => 'Directora territorial Antioquia - UARIV'],
            ['DPND_name' => 'Directora territorial Atlántico - UARIV', 'DPND_description' => 'Directora territorial Atlántico - UARIV'],
            ['DPND_name' => 'Directora territorial Bolívar y San Andrés - UARIV', 'DPND_description' => 'Directora territorial Bolívar y San Andrés - UARIV'],
            ['DPND_name' => 'Directora territorial Caquetá Huila - UARIV', 'DPND_description' => 'Directora territorial Caquetá Huila - UARIV'],
            ['DPND_name' => 'Directora territorial Cauca - UARIV', 'DPND_description' => 'Directora territorial Cauca - UARIV'],
            ['DPND_name' => 'Director territorial Central - UARIV', 'DPND_description' => 'Director territorial Central - UARIV'],
            ['DPND_name' => 'Director territorial Cesar - La Guajira - UARIV', 'DPND_description' => 'Director territorial Cesar - La Guajira - UARIV'],
            ['DPND_name' => 'Dirección territorial Chocó - UARIV', 'DPND_description' => 'Dirección territorial Chocó - UARIV'],
            ['DPND_name' => 'Director territorial de Córdoba - UARIV', 'DPND_description' => 'Director territorial de Córdoba - UARIV'],
            ['DPND_name' => 'Director Territorial Eje Cafetero - UARIV', 'DPND_description' => 'Director Territorial Eje Cafetero - UARIV'],
            ['DPND_name' => 'Directora territorial Magdalena - UARIV', 'DPND_description' => 'Directora territorial Magdalena - UARIV'],
            ['DPND_name' => 'Directora territorial Magdalena Medio - UARIV', 'DPND_description' => 'Directora territorial Magdalena Medio - UARIV'],
            ['DPND_name' => 'Dirección territorial meta, llanos orientales y Amazonía - UARIV', 'DPND_description' => 'Dirección territorial meta, llanos orientales y Amazonía - UARIV'],
            ['DPND_name' => 'Directora territorial Nariño - UARIV', 'DPND_description' => 'Directora territorial Nariño - UARIV'],
            ['DPND_name' => 'Directora territorial Norte de Santander y Arauca - UARIV', 'DPND_description' => 'Directora territorial Norte de Santander y Arauca - UARIV'],
            ['DPND_name' => 'Dirección territorial Putumayo - UARIV', 'DPND_description' => 'Dirección territorial Putumayo - UARIV'],
            ['DPND_name' => 'Director territorial Santander - UARIV', 'DPND_description' => 'Director territorial Santander - UARIV'],
            ['DPND_name' => 'Directora territorial Sucre - UARIV', 'DPND_description' => 'Directora territorial Sucre - UARIV'],
            ['DPND_name' => 'Directora territorial Urabá Darién - UARIV', 'DPND_description' => 'Directora territorial Urabá Darién - UARIV'],
            ['DPND_name' => 'Directora Territorial Valle del Cauca - UARIV', 'DPND_description' => 'Directora Territorial Valle del Cauca - UARIV'],
            ['DPND_name' => 'Agencia Nacional de Tierras - ANT ', 'DPND_description' => 'Agencia Nacional de Tierras - ANT '],
            ['DPND_name' => 'Agencia de Desarrollo Rural - ADR ', 'DPND_description' => 'Agencia de Desarrollo Rural - ADR '],
            ['DPND_name' => 'Banco Agrario de Colombia S.A.', 'DPND_description' => 'Banco Agrario de Colombia S.A.'],
            ['DPND_name' => 'Banco de Comercio Exterior de Colombia - BANCOLDEX', 'DPND_description' => 'Banco de Comercio Exterior de Colombia - BANCOLDEX'],
            ['DPND_name' => 'Centro Nacional de Memoria Histórica de Colombia', 'DPND_description' => 'Centro Nacional de Memoria Histórica de Colombia'],
            ['DPND_name' => 'Agencia para la Reincorporacion y la Normalizacion - ARN ', 'DPND_description' => 'Agencia para la Reincorporacion y la Normalizacion - ARN '],
            ['DPND_name' => 'Consejo Superior de la Judicatura', 'DPND_description' => 'Consejo Superior de la Judicatura'],
            ['DPND_name' => 'Defensoría del Pueblo', 'DPND_description' => 'Defensoría del Pueblo'],
            ['DPND_name' => 'Departamento Administrativo para la Prosperidad Social - DPS ', 'DPND_description' => 'Departamento Administrativo para la Prosperidad Social - DPS '],
            ['DPND_name' => 'Departamento Nacional de Planeación - DNP', 'DPND_description' => 'Departamento Nacional de Planeación - DNP'],
            ['DPND_name' => 'Dirección para la Acción Integral contra Minas Antipersonal - DAICMA', 'DPND_description' => 'Dirección para la Acción Integral contra Minas Antipersonal - DAICMA'],
            ['DPND_name' => 'Consejeria de los derechos Humanos de la  Presidencia de la Republica ', 'DPND_description' => 'Consejeria de los derechos Humanos de la  Presidencia de la Republica '],
            ['DPND_name' => 'Fiscalía General de la Nación', 'DPND_description' => 'Fiscalía General de la Nación'],
            ['DPND_name' => 'Fondo para el Financiamiento del Sector Agropecuario - FINAGRO', 'DPND_description' => 'Fondo para el Financiamiento del Sector Agropecuario - FINAGRO'],
            ['DPND_name' => 'Fundacion Batuta', 'DPND_description' => 'Fundacion Batuta'],
            ['DPND_name' => 'Instituto Colombiano de Bienestar Familiar - ICBF', 'DPND_description' => 'Instituto Colombiano de Bienestar Familiar - ICBF'],
            ['DPND_name' => 'Instituto Colombiano de Crédito y Estudios en el Exterior - ICETEX', 'DPND_description' => 'Instituto Colombiano de Crédito y Estudios en el Exterior - ICETEX'],
            ['DPND_name' => 'Instituto Geográfico Agustín Codazzi - IGAC', 'DPND_description' => 'Instituto Geográfico Agustín Codazzi - IGAC'],
            ['DPND_name' => 'Instituto Nacional de Medicina Legal y Ciencias Forenses', 'DPND_description' => 'Instituto Nacional de Medicina Legal y Ciencias Forenses'],
            ['DPND_name' => 'Ministerio de Agricultura y Desarrollo Rural', 'DPND_description' => 'Ministerio de Agricultura y Desarrollo Rural'],
            ['DPND_name' => 'Ministerio de Comercio Industria y Turismo', 'DPND_description' => 'Ministerio de Comercio Industria y Turismo'],
            ['DPND_name' => 'Ministerio de Defensa Nacional', 'DPND_description' => 'Ministerio de Defensa Nacional'],
            ['DPND_name' => 'Ministerio de Educación Nacional', 'DPND_description' => 'Ministerio de Educación Nacional'],
            ['DPND_name' => 'Ministerio de Justicia y del Derecho ', 'DPND_description' => 'Ministerio de Justicia y del Derecho '],
            ['DPND_name' => 'Ministerio de Salud y Protección Social', 'DPND_description' => 'Ministerio de Salud y Protección Social'],
            ['DPND_name' => 'Ministerio de Vivienda, Ciudad y Territorio', 'DPND_description' => 'Ministerio de Vivienda, Ciudad y Territorio'],
            ['DPND_name' => 'Ministerio del Interior', 'DPND_description' => 'Ministerio del Interior'],
            ['DPND_name' => 'Ministerio del Trabajo', 'DPND_description' => 'Ministerio del Trabajo'],
            ['DPND_name' => 'Policía Nacional de Colombia', 'DPND_description' => 'Policía Nacional de Colombia'],
            ['DPND_name' => 'Registraduría Nacional del Estado Civil', 'DPND_description' => 'Registraduría Nacional del Estado Civil'],
            ['DPND_name' => 'Servicio Nacional de Aprendizaje - SENA', 'DPND_description' => 'Servicio Nacional de Aprendizaje - SENA'],
            ['DPND_name' => 'Superintendencia de Notariado y Registro', 'DPND_description' => 'Superintendencia de Notariado y Registro'],
            ['DPND_name' => 'Unidad Administrativa Especial del Servicio Público de Empleo', 'DPND_description' => 'Unidad Administrativa Especial del Servicio Público de Empleo'],
            ['DPND_name' => 'Unidad de Gestión de Restitución de Tierras Despojadas - URT', 'DPND_description' => 'Unidad de Gestión de Restitución de Tierras Despojadas - URT'],
            ['DPND_name' => 'Unidad Nacional de Proteccion - UNP', 'DPND_description' => 'Unidad Nacional de Proteccion - UNP'],
            ['DPND_name' => 'Fondo Nacional de Garantias - FNG', 'DPND_description' => 'Fondo Nacional de Garantias - FNG'],
            ['DPND_name' => 'Procuraduria General de la Nacion ', 'DPND_description' => 'Procuraduria General de la Nacion '],
            ['DPND_name' => 'Agencia de Renovacion del Territorio ', 'DPND_description' => 'Agencia de Renovacion del Territorio '],
            ['DPND_name' => 'Unidad Administrativa Especial de Organizaciones Solidarias', 'DPND_description' => 'Unidad Administrativa Especial de Organizaciones Solidarias'],
            ['DPND_name' => 'Superintendencia de Industria y Comercio ', 'DPND_description' => 'Superintendencia de Industria y Comercio '],
            ['DPND_name' => 'MINTIC', 'DPND_description' => 'MINTIC'],
            ['DPND_name' => 'Ministerio de Cultura', 'DPND_description' => 'Ministerio de Cultura'],
            ['DPND_name' => 'Cooperación Internacional', 'DPND_description' => 'Cooperación Internacional'],
            ['DPND_name' => 'Organismo de control', 'DPND_description' => 'Organismo de control'],
            ['DPND_name' => 'Entidad privada', 'DPND_description' => 'Entidad privada'],
            ['DPND_name' => 'Persona natural', 'DPND_description' => 'Persona natural'],
            ['DPND_name' => 'Otros', 'DPND_description' => 'Otros'],
            ['DPND_name' => 'Directora Territorial Boyaca - UARIV', 'DPND_description' => 'Directora Territorial Boyaca - UARIV'],
            ['DPND_name' => 'Directora Territorial Tolima - UARIV', 'DPND_description' => 'Directora Territorial Tolima - UARIV'],
            ['DPND_name' => 'SDG - DR - Grupo De Retornos Y Reubicaciones ', 'DPND_description' => 'SDG - DR - Grupo De Retornos Y Reubicaciones '],
            ['DPND_name' => 'DG- Grupo Fortalecimiento Estrategico a Emprendimiento Victimas', 'DPND_description' => 'DG- Grupo Fortalecimiento Estrategico a Emprendimiento Victimas'],
            ['DPND_name' => 'Directora Territorial Ibague - UARIV', 'DPND_description' => 'Directora Territorial Ibague - UARIV'],
            ['DPND_name' => 'Directora Territorial Central -Bogota - UARIV', 'DPND_description' => 'Directora Territorial Central -Bogota - UARIV'],
            ['DPND_name' => 'Directora Territorial Ibague - UARIV', 'DPND_description' => 'Directora Territorial Ibague - UARIV'],

        ];
        $this->db->table('dependencies')->insertBatch($dataDependencies);
    }
}
